import { backtest, engagement, opportunities, risks, roadmap } from "@/lib/data";

export async function GET() {
  const selected = opportunities.find(item => item.id === "returns")!;
  const document = `# Aster & Row — AI investment decision brief

Generated by Northstar Transformation Studio · 04 September 2026

## Decision

${engagement.decision}

## Recommendation

Approve a £${backtest.business_case.year_one_platform_cost_gbp.toLocaleString("en-GB")} controlled pilot for the ${selected.title}. The use case scored ${selected.score}/100 because it combines frequent operational pain, testable evidence, bounded actions and a reusable platform pattern.

## Evidence

- 5,000 synthetic holdout cases; fixed seed ${backtest.metadata.seed}
- Mean handling time: ${backtest.headline.baseline_mean_minutes} to ${backtest.headline.assisted_mean_minutes} minutes (${backtest.headline.mean_time_reduction_pct}% reduction)
- First-contact resolution: ${backtest.headline.baseline_fcr_pct}% to ${backtest.headline.assisted_fcr_pct}% (+${backtest.headline.fcr_uplift_pp} percentage points)
- Policy adherence: ${backtest.headline.assisted_policy_adherence_pct}%
- Unauthorized writes observed: ${backtest.headline.unauthorized_writes} / ${backtest.metadata.cases}
- Modelled year-one net value: £${backtest.business_case.year_one_net_value_gbp.toLocaleString("en-GB")}; payback ${backtest.business_case.payback_months} months

## Delivery gates

${roadmap.map(item => `- **${item.phase} (${item.weeks})** — ${item.outcome}. Gate: ${item.gate}.`).join("\n")}

## Principal risks

${risks.map(item => `- **${item.id}: ${item.risk}** — ${item.control}. Residual: ${item.residual}; owner: ${item.owner}.`).join("\n")}

## Claim boundary

${backtest.metadata.claim_boundary} Annualised value is capacity opportunity and requires finance validation before it may be described as cashable savings.
`;
  return new Response(document, { headers: { "content-type": "text/markdown; charset=utf-8", "content-disposition": "attachment; filename=aster-row-steerco-brief.md" } });
}
